# More examples of Codefresh YAML can be found at
# https://codefresh.io/docs/docs/yaml-examples/examples/

version: "1.0"
# Stages can help you organize your steps in stages
stages:
  - "clone"
  - "build"
  - "test"

steps:
  main_clone:
    title: "codefresh_demo_main_clone"
    type: "git-clone"
    repo: "rkemery/codefresh-demo"
    # CF_BRANCH value is auto set when pipeline is triggered
    # Learn more at codefresh.io/docs/docs/codefresh-yaml/variables/
    revision: "${{CF_BRANCH}}"
    git: "github"
    stage: "clone"
    
  build_my_app:
    title: "codefresh_demo_build_app"
    type: build
    image_name: rkemery/codefresh-demo
    dockerfile: sample-app/codefresh.Dockerfile
    working_directory: '.'
    tag: 'test'
    registry: dockerhub
    build_arguments:
      - NODE_VERSION=12
      - APP_DIR=/usr/src/app

  codefresh_demo_test:
    title: "codefresh_demo_test"
    type: "freestyle" # Run any command
    image: "alpine:latest" # The image in which command will be executed
    working_directory: "${{clone}}" # Running command where code cloned
    commands:
      - "ls"
    stage: "test"