version: "1.0"
stages:
  - "clone"
  - "build"
  - "test"

steps:
  main_clone:
    title: "Cloning main repository..."
    stage: clone
    type: "git-clone"
    repo: "rkemery/codefresh-demo"
    revision: "${{CF_BRANCH}}"
    git: "github"
  build_my_demo_app:
    title: "Building Node.Js Docker Image for Demo App"
    type: build
    image_name: rkemery/codefresh-demo
    dockerfile: Dockerfile
    working_directory: '.'
    tag: 'test'
    registry: dockerhub
    build_arguments:
      - NODE_VERSION=12
      - APP_DIR=/usr/src/app
  run_integration_tests:
    title: "Running integration tests"
    stage: test
    image: '${{build_my_demo_app}}'
    commands:
      - npm test run