# More examples of Codefresh YAML can be found at
# https://codefresh.io/docs/docs/yaml-examples/examples/

version: "1.0"
# Stages can help you organize your steps in stages
stages:
  - "clone"
  - "build"
  - "test"

steps:
  main_clone:
    title: "Cloning repository"
    type: "git-clone"
    repo: "rkemery/codefresh-demo"
    # CF_BRANCH value is auto set when pipeline is triggered
    # Learn more at codefresh.io/docs/docs/codefresh-yaml/variables/
    revision: "${{CF_BRANCH}}"
    git: "github"
    stage: "clone"
    
  BuildMyImage:
    title: Building My Docker image
    type: build
    image_name: codefresh
    dockerfile: sample-app/codefresh.Dockerfile
    tag: 1.0.1
    registry: dockerhub

  test:
    title: "Running test"
    type: "freestyle" # Run any command
    image: "ubuntu:latest" # The image in which command will be executed
    working_directory: "${{clone}}" # Running command where code cloned
    commands:
      - "ls"
    stage: "test"