version: "1.0"
stages:
  - "clone"
  - "build"
steps:
  main_clone:
    title: "Cloning main repository..."
    stage: clone
    type: "git-clone"
    repo: "rkemery/codefresh-demo"
    revision: "${{CF_BRANCH}}"
    git: "github"
  build_demo_app:
    title: "Building Demo App"
    type: build
    image_name: rkemery/codefresh-demo
    dockerfile: Dockerfile
    working_directory: '.'
    tag: 'test'
    registry: dockerhub
  test:
    title: "Running tests"
    type: "freestyle" 
    image: '${{build_demo_app}}'
    environment:
      - CARGO_HOME=/codefresh/volume/cargo    
    commands:
      - "cargo test"
    stage: "test"