version: "1.0"
stages:
  - "clone"
  - "build"
  - "test"

steps:
  main_clone:
    title: "Cloning main repository..."
    stage: clone
    type: "git-clone"
    repo: "rkemery/codefresh-demo"
    revision: "${{CF_BRANCH}}"
    git: "github"
  build_my_demo_app:
    title: "Building Demo App"
    type: build
    image_name: rkemery/codefresh-demo
    dockerfile: Dockerfile
    working_directory: '.'
    tag: 'test'
    registry: dockerhub
    build_arguments:
      - NODE_VERSION=12
      - APP_DIR=/usr/src/app
  my_test:
    type: composition
    working_directory: ${{build_my_demo_app}}
    composition:
      version: '3'
      services:
        codefresh_demo:
          image: ${{build_my_demo_app}}
          ports: 
            - 3000
    composition_candidates:
      codefresh_demo_test:
        image: ${{build_my_demo_app}}
        links:
          - codefresh_demo
        commands: 
          - npm run test