version: "1.0"
stages:
  - "clone"
  - "build"
  - "test"
steps:
  main_clone:
    title: "Cloning Main Repository"
    stage: clone
    type: "git-clone"
    repo: "rkemery/codefresh-demo"
    revision: "${{CF_BRANCH}}"
    git: "github"
  build_demo_app:
    title: "Building Demo Rust App"
    type: build
    image_name: rkemery/codefresh-demo
    no_cache: false
    dockerfile: Dockerfile
    working_directory: '.'
    tag: 'test'
    registry: dockerhub
  test:
    title: "Running Test on App"
    type: "freestyle" 
    image: "rkemery/codefresh-demo:test"
    commands:
      - "curl http://localhost:8000/health"
    stage: "test"