version: "1.0"
stages:
  - "clone"
  - "build"
  - "test"

steps:
  main_clone:
    title: "Cloning main repository..."
    type: "git-clone"
    repo: "rkemery/codefresh-demo"
    revision: "${{CF_BRANCH}}"
    git: "github"
    stage: "clone"
  build_my_app:
    title: "Building Node.Js Docker Image"
    type: build
    image_name: rkemery/codefresh-demo
    dockerfile: Dockerfile
    working_directory: '.'
    tag: 'test'
    registry: dockerhub
    build_arguments:
      - NODE_VERSION=12
      - APP_DIR=/usr/src/app
  test:
    title: "Test"
    type: "freestyle" 
    image: "alpine:latest" 
    working_directory: "${{clone}}" 
    commands:
      - "ls"
    stage: "test"