version: "1.0"
stages:
  - "clone"
  - "build"
  - "test"

steps:
  main_clone:
    title: "Cloning main repository..."
    type: "git-clone"
    repo: "rkemery/codefresh-demo"
    revision: "${{CF_BRANCH}}"
    git: "github"
    stage: "clone"
  build_my_demo_app:
    title: "Building Node.Js Docker Image for Demo App"
    type: build
    image_name: rkemery/codefresh-demo
    dockerfile: Dockerfile
    working_directory: '.'
    tag: 'test'
    registry: dockerhub
    build_arguments:
      - NODE_VERSION=12
      - APP_DIR=/usr/src/app
  unit_test_example:
    title: "Unit Test - npm test"
    image: '${{build_my_demo_app}}'
    commands:
      - npm run test
    stage: test
  simple_test:
    title: "Test - ls working directory"
    type: "freestyle" 
    image: "alpine:latest" 
    working_directory: "." 
    commands:
      - "ls"
    stage: "test"